repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=119]
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: linter_check
        name: linter_check
        entry: ./lint.sh check
        language: system
        types: [python]